;(function(window,document,undefined){var C,aa=aa||{};function ba(a,c,b){return a.call.apply(a.bind,arguments)}function ca(a,c,b){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var b=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(b,d);return a.apply(c,b)}}return function(){return a.apply(c,arguments)}}function da(a,c,b){da=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ba:ca;return da.apply(null,arguments)}
var ea=aa.Ua&&Date.now||function(){return+new Date};mti={bind:function(a,c,b){var d=2<arguments.length?Array.prototype.slice.call(arguments,2):[];return function(){d.push.apply(d,arguments);return c.apply(a,d)}}};var fa={};function ga(a,c){this.g=c||a;this.D=this.g.document;this.b=void 0}C=ga.prototype;C.createElement=function(a,c,b){a=this.D.createElement(a);if(c)for(var d in c)c.hasOwnProperty(d)&&("style"==d?ha(this,a,c[d]):a.setAttribute(d,c[d]));b&&a.appendChild(this.D.createTextNode(b));return a};function D(a,c,b){a=a.D.getElementsByTagName(c)[0];a||(a=document.documentElement);a&&a.lastChild&&a.insertBefore(b,a.lastChild)}C.za=function(a){function c(){b.D.body?a():setTimeout(c,0)}var b=this;c()};
function ia(a){a.parentNode&&a.parentNode.removeChild(a)}function G(a,c){if(!("undefined"!==typeof SVGElement&&a instanceof SVGElement)){for(var b=a.className.split(/\s+/),d=0,e=b.length;d<e;d++)if(b[d]==c)return;b.push(c);a.className=b.join(" ").replace(/\s+/g," ").replace(/^\s+|\s+$/,"")}}
function ja(a,c){if(!("undefined"!==typeof SVGElement&&a instanceof SVGElement)){for(var b=a.className.split(/\s+/),d=[],e=0,f=b.length;e<f;e++)b[e]!=c&&d.push(b[e]);a.className=d.join(" ").replace(/\s+/g," ").replace(/^\s+|\s+$/,"")}}function ka(a,c){if("undefined"!==typeof SVGElement&&a instanceof SVGElement)return!1;for(var b=a.className.split(/\s+/),d=0,e=b.length;d<e;d++)if(b[d]==c)return!0;return!1}
function ha(a,c,b){if(void 0===a.b){var d=a.D.createElement("p");d.innerHTML='<a style="top:1px;">w</a>';a.b=/top/.test(d.getElementsByTagName("a")[0].getAttribute("style"))}a.b?c.setAttribute("style",b):c.style.cssText=b}
C.getComputedStyle=function(a){if("undefined"!=typeof a&&null!=a){if(1!=a.nodeType)return"";var c={};if("undefined"!=typeof a.currentStyle&&null!=a.currentStyle)return c.fontFamily=a.currentStyle.fontFamily,c.fontWeight=a.currentStyle.fontWeight,c.fontStyle=a.currentStyle.fontStyle,c;a=this.D.defaultView.getComputedStyle(a,null);if("undefined"!=typeof a&&null!=a)return c.fontFamily=a.getPropertyValue("font-family"),c.fontWeight=a.getPropertyValue("font-weight"),c.fontStyle=a.getPropertyValue("font-style"),
c}return""};C.A=function(a){if("undefined"!=typeof a&&null!=a){if("undefined"!=typeof a.currentStyle)return a.currentStyle.fontFamily;if(a=this.D.defaultView.getComputedStyle(a,null))return a.getPropertyValue("font-family")}return""};
function ma(a,c){if("undefined"!=typeof c&&null!=c){if("undefined"!=typeof c.currentStyle)return c.currentStyle.fontWeight;var b=a.D.defaultView.getComputedStyle(c,null);if(b){var d=b.getPropertyValue("font-weight");return"bold"==d.toLowerCase()?700:"normal"==d.toLowerCase()?400:b.getPropertyValue("font-weight")}}return""}
function na(a,c){if("undefined"!=typeof c&&null!=c){if("undefined"!=typeof c.currentStyle)return c.currentStyle.fontStyle;var b=a.D.defaultView.getComputedStyle(c,null);if(b)return b.getPropertyValue("font-style")}return""}
function oa(a,c){var b="";if(void 0!=typeof c&&null!=c){void 0!=c&&null!=c&&"INPUT"==c.tagName&&(b+=c.value);c=c.childNodes||c;for(var d="img script noscript iframe object style param embed link meta head title br hr svg path".split(" "),e=0;e<c.length;e++)if(8!=c[e].nodeType&&0>a.indexOf(d,c[e].tagName?c[e].tagName.toLowerCase():"")){var f;f=(f=c[e].parentNode)?"undefined"!=typeof f.currentStyle?f.currentStyle.textTransform:(f=a.D.defaultView.getComputedStyle(f,null))?f.getPropertyValue("text-transform"):
"":void 0;"none"!=f?(f=1!=c[e].nodeType?c[e].nodeValue.replace(/(?:(?:^|\n)\s+|\s+(?:$|\n))/g,"").replace(/\s+/g," "):"",b+=f.toLowerCase()+f.toUpperCase()):b+=1!=c[e].nodeType?c[e].nodeValue.replace(/(?:(?:^|\n)\s+|\s+(?:$|\n))/g,"").replace(/\s+/g," "):""}return b}}C.getElementById=function(a){return this.D.getElementById(a)};
function pa(a,c){if(document.getElementsByClassName)return document.getElementsByClassName(c);var b=[];qa(a.a,document.body,function(a){var e;e=a.className;var f;if(e)for(e=e.split(" "),f=0;f<e.length;f++)if(e[f]===c){b.push(a);break}});return b}
C.F=function(a,c,b,d,e){var f=[],g=this.A(a).split(","),h="",k="",m;a:if(m=!1,g instanceof Array)for(var l=0;l<g.length;l++)if(b instanceof Array)for(var v=0;v<b.length;v++){if(J(g[l])==J(b[v])){m=!0;break a}}else{if(J(g[l])==J(b)){m=!0;break}}else if(b instanceof Array)for(l=0;l<b.length;l++)if(g==b[l]){m=!0;break}if(m)return null;if(b instanceof Array)for(h=0;h<g.length;h++)if(J(g[h])!=c)if(-1<J(g[h]).indexOf(c))for(k=0;k<b.length;k++)""!=b[k]&&(f.push(b[k]),f.push(c));else f.push(g[h]);else if(b instanceof
Array)for(k=0;k<b.length;k++)""!=b[k]&&(d?e?(m=na(this,a),l=ma(this,a),v=J(b[k])+"_"+m.charAt(0)+l/100,f.push(v)):f.push(b[k]):f.push(b[k]),f.push(c));else f.push(b),f.push(c);else if(d)e?(m=na(this,a),l=ma(this,a),e=J(this.A(a)),v=c+"_"+m.charAt(0)+l/100,J(b),b=v.length,b=v.slice(b-2,b),h=100*b.charAt(1),k=b.charAt(0),c==e&&m.charAt(0)==k&&l==h&&(f.push(v),f.push(c))):(f.push(b),f.push(c));else for(h=0;h<g.length;h++)if(J(g[h])!=c)0==J(g[h]).indexOf(c)?""!=b&&(f.push(b),f.push(c)):(f.push(g[h]),
f.push(c));else if(b instanceof Array)for(k=0;k<b.length;k++)""!=b[k]&&(d?e?(m=na(this,a),l=ma(this,a),v=J(b[k])+"_"+m.charAt(0)+l/100,f.push(v)):f.push(b[k]):f.push(b[k]),f.push(c));else f.push(b),f.push(c);f=ra(f);if(0<f.length&&f[0]!=c){b="";for(h=0;h<f.length;h++)b+="'"+f[h]+"'",h!=f.length-1&&(b+=",");b+="";a.setAttribute("data-mtiFont",c);if(d)return a.style.fontWeight="",a.style.fontStyle="",a.style.fontFamily=""+b,a.style.fontFamily;c=""+b;a.style.setProperty?a.style.setProperty("font-family",
""):a.style.setAttribute("font-family","");a.setAttribute("style",a.style.cssText+"font-family:"+c+" !important;")}else return null};function sa(a,c){for(var b=c.parentNode;null!=b;){if(b==a)return!0;b=b.parentNode}return!1}function qa(a,c,b){b(c);for(c=c.firstChild;c;)qa(a,c,b),c=c.nextSibling}C.indexOf=function(a,c){if(a){if(a.indexOf)return a.indexOf(c);for(var b=0;b<a.length;b++)if(a[b]==c)return b}return-1};
function J(a){return a.replace(/^\s|\s$/g,"").replace(/'|"/g,"").replace(/,\s*/g,"|")}function ra(a){for(var c={},b=[],d=0,e=a.length;d<e;++d)c.hasOwnProperty(J(a[d]))||(b.push(J(a[d])),c[J(a[d])]=1);return b}C.A=function(a){if("undefined"!=typeof a&&null!=a){if("undefined"!=typeof a.currentStyle)return a.currentStyle.fontFamily;if(a=this.D.defaultView.getComputedStyle(a,null))return a.getPropertyValue("font-family")}return""};
function ta(a){if(a&&"string"==typeof a){a=a.replace(/\s/g,"").replace(/\n/g,"").replace(/\r/g,"");for(var c="",b=a.length,d=null,e=0;e<b;e++)d=a.charAt(e),-1==c.indexOf(d)&&(c+=d);return c}return""};function K(a,c){this.g=a;this.b=c};function N(a,c,b,d){this.i=null!=a?a:null;this.H=null!=c?c:null;this.b=null!=b?b:null;this.g=null!=d?d:null}var ua=/^([0-9]+)(?:[\._-]([0-9]+))?(?:[\._-]([0-9]+))?(?:[\._+-]?(.*))?$/;N.prototype.toString=function(){return[this.i,this.H||"",this.b||"",this.g||""].join("")};
function O(a){a=ua.exec(a);var c=null,b=null,d=null,e=null;a&&(null!==a[1]&&a[1]&&(c=parseInt(a[1],10)),null!==a[2]&&a[2]&&(b=parseInt(a[2],10)),null!==a[3]&&a[3]&&(d=parseInt(a[3],10)),null!==a[4]&&a[4]&&(/^[0-9]+$/.test(a[4])?e=parseInt(a[4],10):e=a[4]));return new N(c,b,d,e)};function P(a,c,b,d,e,f,g,h){this.N=a;this.ia=c;this.Ba=b;this.Aa=d;this.fa=e;this.b=h}P.prototype.getName=function(){return this.N};function va(){this.c=navigator.userAgent}var wa=new P("Unknown",new N,"Unknown",new N,"Unknown",0,0,new K(!1,!1));
function xa(){var a=new va;if(-1!=a.c.indexOf("MSIE")||-1!=a.c.indexOf("Trident/")){var c=Q(a),b=O(ya(a)),d=null,e=null,f=null,f=R(a.c,/Trident\/([\d\w\.]+)/,1),d=-1!=a.c.indexOf("MSIE")?O(R(a.c,/MSIE ([\d\w\.]+)/,1)):O(R(a.c,/rv:([\d\w\.]+)/,1));""!=f?(e="Trident",f=O(f)):(e="Unknown",f=new N);a=new P("MSIE",d,e,f,c,0,0,new K("Windows"==c&&6<=d.i||"Windows Phone"==c&&8<=b.i,!1))}else if(-1!=a.c.indexOf("Opera"))a:if(c="Unknown",b=O(R(a.c,/Presto\/([\d\w\.]+)/,1)),O(ya(a)),null!==b.i?c="Presto":(-1!=
a.c.indexOf("Gecko")&&(c="Gecko"),b=O(R(a.c,/rv:([^\)]+)/,1))),-1!=a.c.indexOf("Opera Mini/"))d=O(R(a.c,/Opera Mini\/([\d\.]+)/,1)),a=new P("OperaMini",d,c,b,Q(a),0,0,new K(!1,!1));else{if(-1!=a.c.indexOf("Version/")&&(d=O(R(a.c,/Version\/([\d\.]+)/,1)),null!==d.i)){a=new P("Opera",d,c,b,Q(a),0,0,new K(10<=d.i,!1));break a}d=O(R(a.c,/Opera[\/ ]([\d\.]+)/,1));a=null!==d.i?new P("Opera",d,c,b,Q(a),0,0,new K(10<=d.i,!1)):new P("Opera",new N,c,b,Q(a),0,0,new K(!1,!1))}else/OPR\/[\d.]+/.test(a.c)?a=za(a):
/AppleWeb(K|k)it/.test(a.c)?a=za(a):-1!=a.c.indexOf("Gecko")?(c="Unknown",b=new N,O(ya(a)),d=!1,-1!=a.c.indexOf("Firefox")?(c="Firefox",b=O(R(a.c,/Firefox\/([\d\w\.]+)/,1)),d=3<=b.i&&5<=b.H):-1!=a.c.indexOf("Mozilla")&&(c="Mozilla"),e=O(R(a.c,/rv:([^\)]+)/,1)),d||(d=1<e.i||1==e.i&&9<e.H||1==e.i&&9==e.H&&2<=e.b),a=new P(c,b,"Gecko",e,Q(a),0,0,new K(d,!1))):a=wa;return a}
function Q(a){var c=R(a.c,/(iPod|iPad|iPhone|Android|Windows Phone|BB\d{2}|BlackBerry)/,1);if(""!=c)return/BB\d{2}/.test(c)&&(c="BlackBerry"),c;a=R(a.c,/(Linux|Mac_PowerPC|Macintosh|Windows|CrOS|PlayStation|CrKey)/,1);return""!=a?("Mac_PowerPC"==a?a="Macintosh":"PlayStation"==a&&(a="Linux"),a):"Unknown"}
function ya(a){var c=R(a.c,/Windows Phone( OS)? ([^;)]+)/,2);if(c||(c=R(a.c,/(OS X|Windows NT|Android) ([^;)]+)/,2))||(c=R(a.c,/(iPhone )?OS ([\d_]+)/,2)))return c;if(c=R(a.c,/(?:Linux|CrOS|CrKey) ([^;)]+)/,1))for(var c=c.split(/\s/),b=0;b<c.length;b+=1)if(/^[\d\._]+$/.test(c[b]))return c[b];return(a=R(a.c,/(BB\d{2}|BlackBerry).*?Version\/([^\s]*)/,2))?a:"Unknown"}
function za(a){var c=Q(a),b=O(ya(a)),d=O(R(a.c,/AppleWeb(?:K|k)it\/([\d\.\+]+)/,1)),e="Unknown",f=new N,f="Unknown",g=!1;/OPR\/[\d.]+/.test(a.c)?e="Opera":-1!=a.c.indexOf("Edge")?e="Edge":-1!=a.c.indexOf("Chrome")||-1!=a.c.indexOf("CrMo")||-1!=a.c.indexOf("CriOS")?e="Chrome":/Silk\/\d/.test(a.c)?e="Silk":"BlackBerry"==c||"Android"==c?e="BuiltinBrowser":-1!=a.c.indexOf("PhantomJS")?e="PhantomJS":-1!=a.c.indexOf("Safari")?e="Safari":-1!=a.c.indexOf("AdobeAIR")?e="AdobeAIR":-1!=a.c.indexOf("PlayStation")?
e="BuiltinBrowser":-1!=a.c.indexOf("FBAN")&&(e="FBWebUI");"BuiltinBrowser"==e?f="Unknown":"Silk"==e?f=R(a.c,/Silk\/([\d\._]+)/,1):"Chrome"==e?f=R(a.c,/(Chrome|CrMo|CriOS)\/([\d\.]+)/,2):-1!=a.c.indexOf("Version/")?f=R(a.c,/Version\/([\d\.\w]+)/,1):"AdobeAIR"==e?f=R(a.c,/AdobeAIR\/([\d\.]+)/,1):"Opera"==e?f=R(a.c,/OPR\/([\d.]+)/,1):"PhantomJS"==e?f=R(a.c,/PhantomJS\/([\d.]+)/,1):"FBWebUI"==e?f=R(a.c,/FBSV\/([\d.]+)/,1):"Edge"==e&&(f=R(a.c,/Edge\/([\d.]+)/,1));f=O(f);g="AdobeAIR"==e?2<f.i||2==f.i&&
5<=f.H:"BlackBerry"==c?10<=b.i:"Android"==c?2<b.i||2==b.i&&1<b.H:526<=d.i||525<=d.i&&13<=d.H;return new P(e,f,"AppleWebKit",d,c,0,0,new K(g,536>d.i||536==d.i&&11>d.H))}function R(a,c,b){return(a=a.match(c))&&a[b]?a[b]:""};function Aa(a){this.g=a||"-"}Aa.prototype.b=function(a){for(var c=[],b=0;b<arguments.length;b++)c.push(arguments[b].replace(/[\W_]+/g,"").toLowerCase());return c.join(this.g)};function Ba(a,c,b){this.a=a;this.g=c;this.s=b;this.b=new Aa("-")}function Ca(a){G(a.g,a.b.b("mti","loading"));Da(a,"loading")}function Ea(a){ja(a.g,a.b.b("mti","loading"));ka(a.g,a.b.b("mti","active"))||G(a.g,a.b.b("mti","inactive"));Da(a,"inactive")}function Da(a,c,b){if(a.s[c])if(b)a.s[c](b.getName(),S(b));else a.s[c]()};function T(a,c){this.N=a;this.W=4;this.P="n";var b=(c||"n4").match(/^([nio])([1-9])$/i);b&&(this.P=b[1],this.W=parseInt(b[2],10))}T.prototype.getName=function(){return this.N};T.prototype.ya=function(a){var c=[];a=a.split(/,\s*/);for(var b=0;b<a.length;b++){var d=a[b].replace(/['"]/g,"");-1==d.indexOf(" ")?c.push(d):c.push("'"+d+"'")}return c.join(",")};function S(a){return a.P+a.W};function Fa(a,c){this.a=a;this.g=c;this.b=this.a.createElement("span",{"aria-hidden":"true"},this.g)}function Ga(a){D(a.a,"body",a.b)}function Ha(a){var c="position:absolute;top:-999px;left:-999px;font-size:300px;width:auto;height:auto;line-height:normal;margin:0;padding:0;font-variant:normal;white-space:nowrap;font-family:"+a.ya(a.N)+"!important;",b="normal",d=a.W+"00";"o"===a.P?b="oblique":"i"===a.P&&(b="italic");return c+("font-style:"+b+";font-weight:"+d+";")};function Ia(a,c,b,d,e,f,g,h){this.aa=a;this.Ea=c;this.a=b;this.b=d;this.X=h||"BESb\uc5d0swy";this.da=e;this.J={};this.Ha=f||5E4;this.ca=g||null;this.s=this.g=null;a=new Fa(this.a,this.X);Ga(a);for(var k in U)U.hasOwnProperty(k)&&(c=new T(U[k],S(this.b)),ha(a.a,a.b,Ha(c)),this.J[U[k]]=a.b.offsetWidth);ia(a.b)}var U={Ta:"serif",Sa:"sans-serif",Pa:"monospace"};function Ja(a,c,b){for(var d in U)if(U.hasOwnProperty(d)&&c===a.J[U[d]]&&b===a.J[U[d]])return!0;return!1}
function Ka(a){var c=a.g.b.offsetWidth,b=a.s.b.offsetWidth;c===a.J.serif&&b===a.J["sans-serif"]||a.da.b&&Ja(a,c,b)?ea()-a.Fa>=a.Ha?a.da.b&&Ja(a,c,b)&&(null===a.ca||a.ca.hasOwnProperty(a.b.getName()))?La(a,a.aa):La(a,a.Ea):Ma(a):La(a,a.aa)}function Ma(a){setTimeout(da(function(){Ka(this)},a),25)}function La(a,c){ia(a.g.b);ia(a.s.b);c(a.b)};function Na(a,c,b,d){this.a=c;this.b=b;this.g=0;this.J=this.s=!1;this.da=d;this.ca=a.b}
function Oa(a,c,b,d,e){if(0===c.length&&e)Ea(a.b);else for(a.g+=c.length,e&&(a.s=e),e=0;e<c.length;e++){var f=c[e],g=b[f.getName()],h=a.b,k=f;G(h.g,h.b.b("mti",k.getName(),S(k).toString(),"loading"));Da(h,"fontloading",k);f=new Ia(da(a.X,a),da(a.aa,a),a.a,f,a.ca,a.da,d,g);f.g=new Fa(f.a,f.X);Ga(f.g);f.s=new Fa(f.a,f.X);Ga(f.s);f.Fa=ea();g=f.g;h=new T(f.b.getName()+",serif",S(f.b));ha(g.a,g.b,Ha(h));g=f.s;h=new T(f.b.getName()+",sans-serif",S(f.b));ha(g.a,g.b,Ha(h));Ka(f)}}
Na.prototype.X=function(a){var c=this.b;ja(c.g,c.b.b("mti",a.getName(),S(a).toString(),"loading"));ja(c.g,c.b.b("mti",a.getName(),S(a).toString(),"inactive"));G(c.g,c.b.b("mti",a.getName(),S(a).toString(),"active"));Da(c,"fontactive",a);this.J=!0;Pa(this)};Na.prototype.aa=function(a){var c=this.b;ja(c.g,c.b.b("mti",a.getName(),S(a).toString(),"loading"));ka(c.g,c.b.b("mti",a.getName(),S(a).toString(),"active"))||G(c.g,c.b.b("mti",a.getName(),S(a).toString(),"inactive"));Da(c,"fontinactive",a);Pa(this)};
function Pa(a){0==--a.g&&a.s&&(a.J?(a=a.b,ja(a.g,a.b.b("mti","loading")),ja(a.g,a.b.b("mti","inactive")),G(a.g,a.b.b("mti","active")),Da(a,"active")):Ea(a.b))};mti.Na=function(){this.ya='"'};mti.G=function(){this.ga=mti.G.g;this.L=mti.G.s};mti.G.g=["font-style","font-weight"];mti.G.s={"font-style":[["n","normal"]],"font-weight":[["4","normal"]]};mti.G.b=function(a,c,b){this.va=a;this.Ja=c;this.L=b};mti.G.b.prototype.compact=function(a,c){for(var b=0;b<this.L.length;b++)if(c==this.L[b][1]){a[this.va]=this.L[b][0];break}};mti.G.b.prototype.expand=function(a,c){for(var b=0;b<this.L.length;b++)if(c==this.L[b][0]){a[this.va]=this.Ja+":"+this.L[b][1];break}};
mti.G.prototype.compact=function(a){var c=["n","4"];a=a.split(";");for(var b=0,d=a.length;b<d;b++){var e=a[b].replace(/\s+/g,"").split(":");if(2==e.length){var f=e[1];a:{for(var e=e[0],g=0;g<this.ga.length;g++)if(e==this.ga[g]){e=new mti.G.b(g,e,this.L[e]);break a}e=null}e&&e.compact(c,f)}}return c.join("")};
mti.G.prototype.expand=function(a){if(2!=a.length)return null;for(var c=[null,null],b=0,d=this.ga.length;b<d;b++){var e=this.ga[b];(new mti.G.b(b,e,this.L[e])).expand(c,a.substr(b,1))}return c[0]&&c[1]?c.join(";")+";":null};function Qa(a,c,b){this.s=a;this.ta=c;this.c=b;this.b=this.g=0}Qa.prototype.load=function(a){var c=a.context||this.s;this.a=new ga(this.s,c);c=new Ba(this.a,c.document.documentElement,a);if(this.c.b.g){var b=this.ta,d=this.a,e=[],f;for(f in a)if(a.hasOwnProperty(f)){var g=b.b[f];g&&e.push(g(a[f],d))}a=a.timeout;this.b=this.g=e.length;a=new Na(this.c,this.a,c,a);f=0;for(b=e.length;f<b;f++)d=e[f],d.Ma(this.c,da(this.J,this,d,c,a))}else Ea(c)};
Qa.prototype.J=function(a,c,b,d){var e=this;d?a.load(function(a,d,h){Ra(e,c,b,a,d,h)}):(a=0==--this.g,this.b--,a&&(0==this.b?Ea(c):Ca(c)),Oa(b,[],{},null,a))};function Ra(a,c,b,d,e,f){var g=0==--a.g;g&&Ca(c);setTimeout(function(){Oa(b,d,e||{},f||null,g)},0)};var Sa=window,Ta=xa(),Ua=Sa.MonoTypeWebFonts=new Qa(window,new function(){this.b={}},Ta);window.MonoTypeWebFonts.load=Ua.load;mti.qa=4E4;
mti.o=function(a,c,b,d,e){this.T=a;this.c=c;this.a=b;this.f=d;this.Ca={};this.j=e;this.h=[];this.v=!1;this.m={};this.l=d.efg;this.T.mti_element_cache=[];this.ba=[];this.ha=[];this.B=[];this.$={};this.M=[];this.V=[];this.ja=0;this.version=this.I=void 0;this.na=this.u=!1;this.sa={TTF:"truetype",WOFF:"woff",SVG:"svg",MTX:"truetype",OTF:"opentype",WOFF2:"woff2"};1==V.UseTextIndent?this.Z="text-align:left;text-indent:-9999px;font-size:0px":this.Z="visibility:hidden;";this.la=this.f.reqSub||V.EnableDSForAllFonts;
this.I=a=this.c.getName().toLowerCase();this.version=this.c.ia;this.u="msie"===a&&8>=this.version.i?!0:!1;this.na="msie"==a&&8>this.version.i?!0:!1;this.ma={EOT:2,SVG:11,OTF:13,TTF:1,WOFF:3,WOFF2:14}};mti.o.g="monotype";mti.o.b=!1;mti.o.prototype={Ma:function(a,c){var b=this,d=b.f.projectId;if(d){b.T.mti_element_cache=[];Va(b);V.UseHybrid&&(setTimeout(function(){document.documentElement.style.visibility=""},700),V.EnableCustomFOUTHandler=!0,b.U(b.f.pfL,!1,!0));var e=function(){V.UseHybrid&&(window.MonoTypeWebFonts.addEvent("active",function(){Wa(b,b.U,!1)}),window.MonoTypeWebFonts.addEvent("inactive",function(){Wa(b,b.U,!1)}));this.u||b.xa();b.la?b.ka.call(b):b.ka.call(b,!0);c(V.EnableCustomFOUTHandler)};setTimeout(function(){document.documentElement.style.visibility=
""},750);!0===V.isAsync?V.onReady=e:(b.la?Xa(b,e):this.za(function(){b.ka.call(b,!0);c(V.EnableCustomFOUTHandler)}),this.u||!b.f.enableOtf||b.la||Xa(b,b.xa.bind(b)));var f=function(){if(0<b.h.length){var a=[];b.h&&(a=b.h);b.T["__mti_fntLst"+d]=function(){for(var c=[],b=[],d=0;d<a.length;d++)c.push({fontfamily:a[d].N,fontStyle:a[d].P,fontWeight:a[d].W}),b.push(a[d]);return c}}else setTimeout(function(){f()},0)};f()}else c(V.EnableCustomFOUTHandler)},ka:function(a,c){a=this;var b=!1,d={},e={};V.UseHybrid&&
0<a.ja?a.M.length!=a.ja&&(b=!0):b=!0;if(b||null!=a.j){var e=new W(document.body,a.a,a.f.pfL),f=e.K(document.body),d=e.Y(),e=e.C;null!=a.j&&mti.bind(a.j,a.j.load,e)();if(c)"";else for(var b=a,g=e,h=0;h<g.length;h++)for(var k in b.m)-1<b.a.A(g[h]).indexOf(k)&&(void 0==g[h].getAttribute("id"),b.a.F(g[h],k,b.m[k],b.u,b.v))}k=[];for(b=0;b<a.f.pfL.length;b++){var g=a.f.pfL[b],m,l,v,h=g.enableSubsetting,z=g.enableOtf,r=g.contentIds,y=g.subsetOption;if(!g.enableSubsetting){void 0!=g.fontWeight&&void 0!=g.fontStyle&&
(l=g.fontWeight,v=g.fontStyle,m=v.charAt(0)+l/100);var u=new T(g.fontfamily,m);u.fontfamily=g.fontfamily;u.fontWeight=void 0!=g.fontWeight?l:"4";u.fontStyle=void 0!=g.fontStyle?v:"n";u.enableSubsetting=h;u.contentIds=r;u.enableOtf=z;u.subsetOption=y;k.push(u)}}m=k;l=null==m?0:m.length;v={};b=[];for(k=0;k<l;k+=1)v[m[k].N+"||"+m[k].W+"||"+m[k].P]=m[k];for(k in v)b.push(v[k]);k=b;Ya(a,d,f,"",!0);Ya(a,k,f,"",!1);a.T.mti_element_cache=e}};MonoTypeWebFonts.ta.b[mti.o.g]=function(a){var c=xa(),b=new ga(window),d=null;a.enableOtf&&(d=new mti.Qa(b,c,a));c=new mti.o(window,c,b,a,d);if(a.reqSub||V.EnableDSForAllFonts||a.enableOtf){var e=new mti.ra(c);window.MonoTypeWebFonts.renderPartial=function(a,c){e.Ka(a,c)}}return c};
var Za={ec:"true",dfcURL:"http://api2.fonts.com/FontSubsetter.ashx",fontdataversion:"v2",sO:"true",ffArray:{safari:{"3.1":"ttf","5.1":"woff"},msafari:{1:"svg","4.2":"ttf","5.1":"woff"},chrome:{3:"svg",4:"ttf",5:"woff",36:"woff2"},opera:{10:"ttf","11.10":"woff","26.0":"woff2"},msie:{4:"eot",9:"woff"},mozilla:{"3.5":"ttf","3.6":"woff","39.0":"woff2"},edge:{12:"woff"}},bsmcArray:{safari:{"3.1":"2000","5.1":"15600"},msafari:{1:"15600"},chrome:{3:"15600"},opera:{10:"15600"},msie:{4:"1000",9:"3000"},mozilla:{"3.5":"15600"},
edge:{12:"15600"}},fctypeArray:{ttf:"1",eot:"2",woff:"3",svg:"11",otf:"13",woff2:"14"},specialChar:"%u201C %u201D %u2200 %u2202 %u2203 %u2205 %u2207 %u2208 %u2209 %u220B %u220F %u2211 %u2018 %u2019 %B0 %u2026 %u2122 %A9 %AE %u2014 %u2013 %A7 %B1 %B7 %u2032 %u2033 %u20AC %u2248 %u2260 %u2264 %u2265 %u221A %u221D %u2220 %u2225 %u2227 %u2228 %u2229 %u222A %u222B %u222E %u2234 %u2235 %u2236 %u2237 %u223D %u224C %u2261 %u226E %u226F %u2299 %u22A5 %u0391 %u0392 %u0393 %u0394 %u0395 %u0396 %u0397 %u0398 %u0399 %u039A %u039B %u039C %u039D %u039E %u039F %u03A0 %u03A1 %u03A3 %u03A4 %u03A5 %u03A6 %u03A7 %u03A8 %u03A9 %u221E %u2190 %u2191 %u2192 %u2193 %u2640 %u2642 + %22 %5C %23 %26 %3F %B7 %3B %3A".split(" ")};
function X(a,c){return void 0!=Za[c]?Za[c]:a.f[c]};function Ya(a,c,b,d,e){var f,g="TTF",h=a.f.projectId,k=X(a,"ec"),m=a.f.fcURL,l=X(a,"dfcURL"),v=a.a.createElement("style",{type:"text/css",id:"mti_fontface_"+(d?"Aj_":"")+a.f.projectId}),z="",r=!1,y={},u={};a.m={};var n=null,x=null;void 0!=V.CustomDfcURL&&(l=V.CustomDfcURL);c||(c=[]);for(var t=0;t<c.length;t++){var q=c[t],p=c[t].fontfamily,w=c[t].contentIds,B=c[t].enableOtf,A=q.subsetOption,g=null;a.l&&(n=c[t].fontWeight,x=c[t].fontStyle,g=x.charAt(0)+n/100,a.v=!0);e&&(null==g?new T(p):new T(p,g),
a.h.push(c[t]));var g=a.S(w),H="";a.l?H=p+"_"+x.charAt(0)+n/100:H=p+"_n4";q=1==V.EnableDSForAllFonts?!0:q.enableSubsetting;var u=a,I=n,M=x,F=w[g.toUpperCase()],L=u.c.getName(),L=L.toLowerCase();f=u.c.ia;"mozilla"==L.toLowerCase()&&"Unknown"==f&&(L="msie");f="?";k&&(f+=a.f.ck+"&");f+="fctypeId="+X(u,"fctypeArray")[g]+"&fcId="+w.TTF+"&origId="+F;f+="&projectId="+h;f+="&content=";F="";if(b){var E=null;(E=$a(b,p,I,M))?"":E="";var E=E.split("::"),I=E[0],M=E[1],pb=I.split("").sort().join(""),E="";I&&(E=
pb.replace('"',"").replace("?","").replace(";","").replace("#","").replace("&",""));if(E&&0<E.length||M&&0<M.length)F+=("msie"==L?E||"":encodeURIComponent(E||""))+"BESb\uc5d0swyMm",""!=M&&(F+=M)}L=f+F;F=X(u,"bsmcArray");E=u.I;"firefox"==E&&(E="mozilla");/ipad|ipod|iphone/.test(u.c.fa.toLowerCase())&&(u.I="msafari");u=u.version.i;F=F[E];E="";I=void 0;for(I in F)parseFloat(u)>=parseFloat(I)&&(E=F[I]);u=E;f=L.length>u?Math.ceil(L.length/(u-f.length)):1;L=f;u=!1;a.na&&1<L&&(L=1,u=!0,q=!1);f="";if(1<L||
d){if(null!==b){r=!0;y[H]||(y[H]=[]);if(b)var ab=b[H];if(ab){u=[];F="";E=F=(d?25<p.length?p.substring(0,20):p:p)+(d?d:"");a.u&&a.l?E+="_"+x.charAt(0)+n/100:a.l?E+="_"+x.charAt(0)+n/100:E+="_n4";y[H].push(E);b[E]=ab;if(f=1<L?Y(a,w,h,!1,m,l,a.f.ck,F,n,x,b,g,B,d):Y(a,w,h,q,m,l,a.f.ck,F,n,x,b,g,B,d,A))B="",a.u&&void 0!=x&&void 0!=n?B=E:B=F,z=bb(a,B,"",z,n,x,B,f,g,w,!0,"",!1,!0,d,la,!1),a.u&&a.l&&!d&&(F+="_"+x.charAt(0)+n/100),u.push("'"+F+"'"),a.V[p]=F;a.m[p]=u}else a.u&&!q&&(a.u&&a.l&&(p+="_"+x.charAt(0)+
n/100),(f=Y(a,w,h,q,m,l,a.f.ck,p+(d?d:""),n,x,u?null:b,g,B,d,A))&&(z=bb(a,p,"",z,n,x,p,f,g,w,!0,"",!1,!0,d,la,!1)))}}else if(f=Y(a,w,h,q,m,l,a.f.ck,p+(d?d:""),n,x,u?null:b,g,B,d,!1,A)){var la="";a.u&&a.l&&(la="_"+x.charAt(0)+n/100,a.m[p]=p+la);cb(A)&&(g=db(a));z=bb(a,p,"",z,n,x,p,f,g,w,!0,"",!1,!0,d,la,!1)}}if(!0===r||d)d?Va(a,y,d):Va(a,y);""!=z&&D(a.a,"head",v);v.styleSheet?v.styleSheet.cssText=z:v.appendChild(document.createTextNode(z))}
function Y(a,c,b,d,e,f,g,h,k,m,l,v,z,r,y,u){function n(l){var n=a.f.env;e=e.replace("http://","").replace("https://","");f=f.replace("http://","").replace("https://","");e="https://"+e+(z?"ot/":"");f="https://"+f;if(cb(l))if(t=f+"?",t+=g+"&",t+="fctypeId="+("14"==X(a,"fctypeArray")[db(a)]?"3":X(a,"fctypeArray")[db(a)])+"&fcId="+c.TTF,t+="&env="+n,void 0!=l){var n=l.unicode,p=l.text;l=l.lang;void 0!=n&&(t+="&ranges="+n);void 0!=p&&(t+="&content="+p);void 0!=l&&(t+="&languages="+l)}else t="";else d?
(t=f+"?",t+=g+"&",t+="fctypeId="+("15"==X(a,"fctypeArray")[v]?"3":X(a,"fctypeArray")[v])+"&fcId="+c.TTF+"&origId="+x,t+="&env="+n):(""!==a.ma[v.toUpperCase()]?e+=a.ma[v.toUpperCase()]+"/":e+=a.ma.WOFF+"/",t=e+x+"."+v.toLowerCase()+"?"+g,a.l?B=m.charAt(0)+k/100:B="n4",-1<a.a.indexOf(a.M,h+"_"+B)&&(t=""),0>a.a.indexOf(a.M,h+"_"+B)&&!y&&!z&&!r&&a.M.push(h+"_"+B)),""!=t&&(t+="&projectId="+b,null!=v&&"SVG"==v.toUpperCase()&&(t+="#"+x));return t}var x=c[v.toUpperCase()],t,q,p,w,B;V.UseHybrid&&(w=h+"_n4_f",
a.l?(B=m.charAt(0)+k/100,w=(25<h.length?h.substring(0,20):h)+"_"+B+"_f"):B="n4",1==d&&Z(w)&&(d=!1));if(cb(u))t=n(u);else if(d||V.EnableDSForAllFonts){if(l){l=$a(l,h,k,m);if(null==l)return t="";if(l){w=l.split("").sort().join("");l=h;a.v&&(l+="_"+m.charAt(0)+k/100);w=eb(a,w,l,r);r&&(a.v?l=l.substring(0,l.length-8)+"_"+m.charAt(0)+k/100:l=l.substring(0,l.length-5)+"_n4",a.$[l]=w);w=fb(a,w).split("::");l=w[0];w=w[1].replace(":","");l&&(p=l.replace('"',"").replace("?","").replace(";","").replace("#",
"").replace("&",""));if(p&&0<p.length||w&&0<w.length)q="&content="+(p||"")+"BESb\uc5d0swyMm",""!=w&&(q+=w);t=n(u)+q}else return}}else n(u);return t}
mti.o.prototype.U=function(a,c,b){if(!(null!=a&&1>a.length)){var d=this.f.projectId,e=this.f.fcURL,f=this.f.ck,g="",h,k,m=this.c.ia,l=this.c.getName(),l=l.toLowerCase(),v="msie"==l&&8>=m?!0:!1,z="msie"==l?!0:!1,m=!1,r={TTF:"truetype",WOFF:"woff",SVG:"svg",MTX:"truetype",OTF:"opentype",WOFF2:"woff2"},l=[];a=b?a:this.h;for(var y=0,u="n4",n=0;n<this.f.pfL.length;n++){var x=this.f.pfL[n],t=!1,q=x.fontfamily;x.enableSubsetting&&this.ja++;if(b)t=!0;else for(var p=0;p<a.length;p++)if(a[p].fontfamily==q&&
(x.enableSubsetting||V.EnableDSForAllFonts)&&(this.v?a[p].fontWeight==x.fontWeight&&a[p].fontStyle==x.fontStyle&&(t=!0,h=x.fontWeight,k=x.fontStyle,u=k.charAt(0)+h/100,y=(25<q.length?q.substring(0,20):q)+"_"+u+"_f"):(y=q+"_n4_f",t=!0),t)){y=p;a.splice(y,1);break}t&&(y=q+"_n4_f",x.enableSubsetting||V.EnableDSForAllFonts)&&((void 0!=x.fontWeight&&void 0!=x.fontStyle&&(h=x.fontWeight,k=x.fontStyle,u=k.charAt(0)+h/100,y=(25<q.length?q.substring(0,20):q)+"_"+u+"_f"),l.push(y),contentIdArray=x.contentIds,
enableOtf=x.enableOtf,Z(y)||b)?Z(y)&&b&&(this.h.push(new T(q,u)),fFormat=this.S(contentIdArray),fontURL=Y(this,contentIdArray,d,!1,e,"",f,q,h,k,null,fFormat,enableOtf,!1,!1),""!=fontURL&&(x="",this.u&&this.l&&(x="_"+k.charAt(0)+h/100),this.ba.push(y),g=bb(this,q,"",g,h,k,q,fontURL,fFormat,contentIdArray,!0,"",!1,!0,!1,x,!1))):(m=!0,0>this.a.indexOf(this.ba,y)&&(fFormat=this.S(contentIdArray),fontURL=Y(this,contentIdArray,d,!1,e,"",f,q,h,k,null,fFormat,enableOtf,!1,!0),""!=fontURL&&(this.ba.push(y),
v&&void 0!=k&&void 0!=h&&(q+="_"+k.charAt(0)+h/100),g+='@font-face{\nfont-family:"'+y+'";',g+='\nsrc:url("'+fontURL+'")',null!=fFormat&&"EOT"==fFormat.toUpperCase()||"MTX"==fFormat.toUpperCase()||(q=r[fFormat.toUpperCase()],contentIdArray[fFormat.toUpperCase()]||(q=r.TTF),g+=" format('"+q+"')"),g+=";}\n"))))}""!=g&&(b=this.a.getElementById("mti_fontface_"+d),null==b&&(b=this.a.createElement("style",{type:"text/css",id:"mti_fontface_"+(c?"Aj_":"")+this.f.projectId}),""!=g&&D(this.a,"head",b)),b.styleSheet?
""!=b.styleSheet.cssText?(b=this.a.getElementById("mti_fontface_"+(c?"hybridAjaxIE_":"hybridIE_")+this.f.projectId),null==b&&(b=this.a.createElement("style",{type:"text/css",id:"mti_fontface_"+(c?"hybridAjaxIE_":"hybridIE_")+this.f.projectId}),""!=g&&D(this.a,"head",b)),b.styleSheet.cssText=g):b.styleSheet.cssText=g:(z&&(b=this.a.getElementById("mti_fontface_"+(c?"hybridAjaxIE_":"hybridIE_")+this.f.projectId),null==b&&(b=this.a.createElement("style",{type:"text/css",id:"mti_fontface_"+(c?"hybridAjaxIE_":
"hybridIE_")+this.f.projectId}),""!=g&&D(this.a,"head",b))),b.innerHTML+=g));if(m){c=[];for(g=0;g<l.length;g++)c.push(new T(l[g]));Oa(new Na(this.c,this.a,new Ba(this.a,document.documentElement,{fontactive:function(a){if("_f"==a.substr(a.length-2)&&!Z(a)){var c=new Date;a=a.replace(/\s+/g,"%20");c.setDate(c.getDate()+1);document.cookie=a+"="+("1; expires="+c.toUTCString())}}}),6E5),c,{},{},!1)}}};var V=window.MTIConfig||{Xa:!1,Oa:!1,Ra:!1};function W(a,c,b,d){this.La=a;this.a=c;this.Ia=b;this.O={};this.C=[];this.h=[];d?this.wa=d:!1;this.Da="img script noscript iframe object style param embed link meta head title br hr svg path".split(" ")}
W.prototype=function(){function a(c,b,d){if(void 0!==c&&null!==c&&""!==c&&c.tagName&&1===c.nodeType)for(0>d.a.indexOf(d.Da,c.tagName.toLowerCase())&&(b?d.ua(c,b):d.ua(c)),c=c.firstChild;c;)a(c,b,d),c=c.nextSibling}return{ua:function(a,b){var d=this.Ia,e=this.a.getComputedStyle(a),f=e.fontFamily,g="",h=e.fontStyle,k=0,m=0,l="",f=(f||"").replace(/^\s|\s$/g,"").replace(/'|"/g,"").replace(/,\s*/g,"|");if(""!=f)for(var v=f.split("|"),z="",k=0;k<v.length;k++)for(m=0;m<d.length;m++){var r=d[m],z=r.fontfamily,
y,u,n=r.enableSubsetting,x=r.enableOtf,t=r.contentIds,q=r.subsetOption,p=!1,w=z,B=new RegExp("^("+v[k]+")$","ig");if(void 0!=r.fontWeight&&void 0!=r.fontStyle)y=r.fontWeight,u=r.fontStyle,l=u.charAt(0)+y/100,g="normal"==e.fontWeight?400:"bold"==e.fontWeight?700:e.fontWeight;else{var A="h1 h2 h3 h4 h5 h6 strong b".split(" ");1==a.nodeType&&(g=0<=this.a.indexOf(A,a.tagName.toLowerCase())?400:"normal"==e.fontWeight?400:"bold"==e.fontWeight?700:400)}if(void 0!=y||void 0!=u)w+="_"+l;var A=z.replace(/^\s|\s$/g,
""),H=w.replace(/^\s|\s$/g,""),I=B.test(A),B=B.test(H);if(I||B)void 0!=y||void 0!=u?w==f?(p=new T(H),p.fontfamily=A,p.fontWeight=y,p.fontStyle=u,p.enableSubsetting=n,p.contentIds=t,p.enableOtf=x,p.subsetOption=q,this.h.push(p),this.C.push(a),p=!0):g==y&&h==u&&(p=new T(A,l),p.fontfamily=A,p.fontWeight=y,p.fontStyle=u,p.enableSubsetting=n,p.contentIds=t,p.enableOtf=x,p.subsetOption=q,this.h.push(p),this.C.push(a),p=!0):(l="n4",p=new T(A),p.fontfamily=A,p.fontWeight=g/100,p.fontStyle=h.charAt(0),p.enableSubsetting=
n,p.contentIds=t,p.enableOtf=x,p.subsetOption=q,this.h.push(p),this.C.push(a),p=!0),p&&(1==V.EnableCustomFOUTHandler&&G(a,b?"mti_font_element"+b:"mti_font_element"),n=a.getAttribute("style"),(n=null!=n?"string"==typeof n?n:"cssText"in n?n.cssText:"":"")&&-1<this.a.indexOf(n,"font-weight")&&-1<this.a.indexOf(n,"font-style")?z+="_"+h.charAt(0)+g/100:z+=1<l.length?"_"+l:"",this.wa||!r.enableSubsetting&&!V.EnableDSForAllFonts||(r="",r=oa(this.a,a),this.O[z.replace(/^\s|\s$/g,"")]&&(r+=this.O[z.replace(/^\s|\s$/g,
"")]),this.O[z.replace(/^\s|\s$/g,"")]=r))}},K:function(c,b){a(this.La,b,this);var d=!1,e;for(e in this.O)if(d=!0,this.wa)break;else this.O[e]=ta(this.O[e]);return d?this.O:null},Y:function(){var a=this.h,b=null==a?0:a.length,d={},e,f=[];for(e=0;e<b;e+=1)d[a[e].N+"||"+a[e].W+"||"+a[e].P]=a[e];for(e in d)f.push(d[e]);return this.h=f},Wa:function(){return this.C}}}();mti.o.prototype.S=function(a){var c=X(this,"ffArray"),b=this.I,d=this.version.i+this.version.H/10;"firefox"==this.I&&(b="mozilla");/ipad|ipod|iphone/.test(this.c.fa.toLowerCase())&&(b="msafari");var c=c[b],b="",e;for(e in c)parseFloat(d)>=parseFloat(e)&&a[c[e].toUpperCase()]&&(b=c[e]);return b};function gb(){for(var a="",c=0;5>c;c++)a+="abcdefghijklmnopqrstuvwxyz".charAt(Math.floor(26*Math.random()));return a}
function hb(a,c){for(var b=0,d=0,e=!1,b=0;b<c.length;b++){e=!1;for(d=0;d<a.length;d++)c[b]==a[d]&&(e=!0);if(0==e&&d==a.length)return 0}return 1}mti.o.prototype.pa=function(a){if((a.ctrlKey||a.metaKey)&&116==a.keyCode){a.preventDefault();a=document.cookie.split(";");for(var c=1;c<=a.length;c++){var b=a[c-1].split("="),d=b[0].substr(b[0].length-2);"1"==b[1]&&"_f"==d&&(document.cookie=b[0]+"=;expires=Thu, 01 Jan 1970 00:00:00 GMT")}document.location.reload(!0)}};
function fb(a,c){var b=X(a,"specialChar"),d=b.length.toString().length;if(c&&"string"==typeof c){c=c.replace(/\s/g,"").replace(/\n/g,"").replace(/\r/g,"");for(var e="",f=c.length,g=null,h="",k=[],m=0;m<f;m++)if(g=c.charAt(m),-1<a.a.indexOf(b,escape(g))){if(-1==a.a.indexOf(k,g)){k.push(g);g=a.a.indexOf(b,escape(g));if(g.toString().length<d)var l=Array(1+d).join("0"),g=(l+g).slice(-l.length);h+=g}}else-1==a.a.indexOf(e,g)&&(e+=g);return e+"::"+h}return""}
function $a(a,c,b,d){var e="";c=void 0!=b&&void 0!=d?c+("_"+d.charAt(0)+b/100):c+"_n4";a&&a[c]&&(e=a[c]);return 0<e.length?e:null}mti.o.prototype.Y=function(){return this.h};mti.o.prototype.load=function(a){a(this.h,this.Ca)};
function Va(a,c,b){var d=new Aa("-"),e=a.a.createElement("style",{type:"text/css",id:"mti_stylesheet_"+(b?"Aj_":"")+a.f.projectId}),f="";if(1==V.EnableCustomFOUTHandler||1==V.UseHybrid){for(var g=a.f.pfL,f=f+(".mti-loading .mti_font_element"+(b?"_Aj":"")+"{"+a.Z+"}\n"),h=0;h<g.length;h++){var k=g[h].fontfamily,m="4",l="n";a.l&&(m=g[h].fontWeight/100,l=g[h].fontStyle.charAt(0),a.u&&(k=k+"_"+l+m,m="4",l="n"));b&&(k=k+b);k&&(f+="."+d.b("mti",k,l+m,"loading")+" .mti_font_element"+(b?b:"")+"{"+a.Z+"}\n")}f+=
".mti_hide_element{"+a.Z+"}"}for(h in a.f.selectorFontMap)if(d=a.f.selectorFontMap[h],k=d.familyName,a.l?(l=d.fontStyle,m=d.fontWeight):(l="normal",m="400"),c&&c[k]&&0<c[k].length&&(k=c[k].join("','")),b||(f=bb(a,k,h,f,m,l,"","","","",!1,d,!0)),1==V.EnableCustomFOUTHandler)for(l in f+="/*fout specific code:*/\n",m=h.split(","),l=void 0,m)f+=".mti-loading "+m[l]+"{"+a.Z+"}\n";""!=f&&D(a.a,"head",e);e.styleSheet?e.styleSheet.cssText=f:e.appendChild(document.createTextNode(f))}
function bb(a,c,b,d,e,f,g,h,k,m,l,v,z,r,y,u,n){1<a.a.indexOf(g,y)?y="":"";r?d+='@font-face{\nfont-family:"'+g+(y?y:"")+(u?u:"")+'";':"";a.u&&a.l&&!n&&(c+="_"+f.charAt(0)+e/100);r?"":d+=b+"{font-family:'"+c+"';";0==a.u&&a.l&&!n&&(d=d+("\n font-style:"+f+";")+("\n font-weight:"+e+";"));h?d+='\nsrc:url("'+h+'")':"";l?(c=d,null!=k&&"EOT"==k.toUpperCase()||"MTX"==k.toUpperCase()||(b=a.sa[k.toUpperCase()],m[k.toUpperCase()]||(b=a.sa.TTF),c+=" format('"+b+"')"),d=c):"";z?(k=d,null!=a.j&&(m=v.otf,v=v.vrnt,
m&&null!=m&&""!=m&&(k+=a.j.Va(m,v))),d=k):"";return d+=";}\n"}mti.o.prototype.za=function(a){function c(){document.body?a():setTimeout(c,0)}c()};mti.o.prototype.S=function(a){var c=X(this,"ffArray"),b=this.I,d=this.version.i+this.version.H/10;"firefox"==this.I&&(b="mozilla");/ipad|ipod|iphone/.test(this.c.fa.toLowerCase())&&(b="msafari");var c=c[b],b="",e;for(e in c)parseFloat(d)>=parseFloat(e)&&a[c[e].toUpperCase()]&&(b=c[e]);return b};
function db(a){var c=X(a,"ffArray"),b=a.I,d=a.version.i+a.version.H/10;"firefox"==a.I&&(b="mozilla");/ipad|ipod|iphone/.test(a.c.fa.toLowerCase())&&(b="msafari");a=c[b];var c="",e;for(e in a)parseFloat(d)>=parseFloat(e)&&(c=a[e]);return c}function cb(a){var c=!1;void 0!=typeof a&&null!=a&&""!=a&&(void 0!=typeof a.lang&&null!=a.lang&&""!=a.lang?c=!0:void 0!=typeof a.unicode&&null!=a.unicode&&""!=a.unicode?c=!0:void 0!=typeof a.text&&null!=a.text&&""!=a.text&&(c=!0));return c};function ib(a,c,b){if(!window.MutationObserver||b){var d="string"==typeof c?document.getElementById(c):c;if(null!==d){b=!0;a.h=[];var e=a.f.projectId,f=a.f.fcURL,g=a.f.ck,h="",k,m;b=a.c.ia;var l="msie"==a.c.getName().toLowerCase()&&8>=b?!0:!1,v={TTF:"truetype",WOFF:"woff",SVG:"svg",MTX:"truetype",OTF:"opentype",WOFF2:"woff2"};b=!0;if(V.UseHybrid){b=!1;var z=a.a.getElementById("mti_fontface_"+e);null==z&&(z=a.a.createElement("style",{type:"text/css",id:"mti_fontface_"+e}),D(a.a,"head",z));var r=d.getAttribute("data-mtiFont"),
y=a.a.getComputedStyle(d);null==r&&(r=y.fontFamily.replace(/^\s|\s$/g,"").replace(/'|"/g,""));for(var u=[],n=0;n<a.f.pfL.length;n++)u.push(a.f.pfL[n].fontfamily);if(d.hasChildNodes&&0>a.a.indexOf(u,r))for(n=d.childNodes,q=0;q<n.length&&!(1==n[q].nodeType&&(r=a.a.A(n[q]).replace(/^\s|\s$/g,"").replace(/'|"/g,""),-1<a.a.indexOf(u,r)));q++);for(var x="normal"==y.fontWeight?"400":"bold"==y.fontWeight?"700":y.fontWeight,y=y.fontStyle,n=y.charAt(0)+x/100,t=r.split(","),q=0;q<t.length;q++){for(var p=t[q]+
"_f",w,B=!1,n=0;n<a.f.pfL.length;n++){w=a.f.pfL[n];var A=w.fontfamily;if(t[q]==A&&w.enableSubsetting)if(void 0!=w.fontWeight&&void 0!=w.fontStyle){if(k=w.fontWeight,m=w.fontStyle,y==w.fontStyle&&x==w.fontWeight){B=!0;n=m.charAt(0)+k/100;p=(25<A.length?A.substring(0,20):A)+"_"+n+"_f";a.h.push(new T(A,n));break}}else{a.h.push(new T(A));B=!0;break}}if(Z(p)&&B)if(l&&-1<a.a.indexOf(a.M,r)){if(a.a.F(d,A,p,!1,!1),d.hasChildNodes)for(n=d.childNodes,q=0;q<n.length;q++)1==n[q].nodeType&&(r=a.a.A(n[q]).replace(/^\s|\s$/g,
"").replace(/'|"/g,""),-1<a.a.indexOf(u,r)&&a.a.F(n[q],A,p,!1,!1))}else{b=!1;contentIdArray=w.contentIds;enableOtf=w.enableOtf;fFormat=a.S(contentIdArray);w=A;l&&(void 0!=m&&void 0!=k?w+="_"+m.charAt(0)+k/100:w+="_n4");fontURL=Y(a,contentIdArray,e,!1,f,"",g,w,k,m,null,fFormat,enableOtf);""!=fontURL&&(h+='@font-face{\nfont-family:"'+w+'";',0==l&&void 0!=k&&void 0!=m&&(h+="\nfont-style:"+m+";",h+="\nfont-weight:"+k+";"),h+='\nsrc:url("'+fontURL+'")',null!=fFormat&&"EOT"==fFormat.toUpperCase()||"MTX"==
fFormat.toUpperCase()||(k=v[fFormat.toUpperCase()],contentIdArray[fFormat.toUpperCase()]||(k=v.TTF),h+=" format('"+k+"')"),h+=";}\n");if(z.styleSheet){if(z.styleSheet.cssText+=h,a.u&&(a.a.F(d,A,w,!1,!1),d.hasChildNodes))for(n=d.childNodes,q=0;q<n.length;q++)1==n[q].nodeType&&(r=a.a.A(n[q]).replace(/^\s|\s$/g,"").replace(/'|"/g,""),-1<a.a.indexOf(u,r)&&a.a.F(n[q],A,w,!1,!1))}else z.innerHTML+=h;a.$[w]=eb(a,"",w);if(!l&&(d.style.fontFamily=""+r,d.removeAttribute("data-mtiFont"),A="",d.hasChildNodes()))for(A=
d.childNodes,h=0;h<A.length;h++)1==A[h].nodeType&&A[h].getAttribute("data-mtiFont")&&(A[h].style.fontFamily=A[h].getAttribute("data-mtiFont"),A[h].removeAttribute("data-mtiFont"));if(null!=a.j){var H=new W(document.getElementById(c).parentElement,a.a,a.f.pfL);H.K({},I);mti.bind(a.j,a.j.ea,H.C)()}break}else b=!0}}if(b){var I=gb(),M=H=null,F=[],L=[],E=null!=d?d.parentElement:document.body;(function(){H=new W(E,a.a,a.f.pfL);M=H.K({},I);var b=[];if(void 0!=M)for(var e in M)e+=I,b.push(new T(f));a.T.mti_element_cache=
H.C;Ya(a,H.Y(),M,I,!0);b=H.C;null!=a.j&&(e=[],e.push(d),mti.bind(a.j,a.j.ea,e)());for(e=0;e<b.length;e++)for(var f in a.m)-1<a.a.indexOf(a.a.A(b[e]),f)&&(b[e].getAttribute("id")==c||b[e]==c?a.a.F(b[e],f,a.m[f],l,a.v):sa(d,b[e])&&-1<a.a.indexOf(a.a.A(b[e]).replace(/'|"/g,""),f)&&a.a.F(b[e],f,a.m[f],l,a.v));e=null==a.m[f]?0:a.m[f].length;if(0<a.h.length)for(b=0;b<a.h.length;b++)f=a.h[b].getName()+I,e=null,a.v&&(e=S(a.h[b])),f=a.u&&null!=e?new T(f+"_"+e):null==e?new T(f):new T(f,e),F.push(f);else for(b=
0;b<e;b++)a.v?F.push(new T(a.m[f][b],"i6")):F.push(new T(a.m[f][b])),-1==a.a.indexOf(a.ha,f)&&(a.ha.push(f),a.v?L.push(new T(a.m[f][b],"i6")):L.push(new T(a.m[f][b])))})();1==V.RemoveMTIClass&&setTimeout(function(){jb(a,"mti_font_element"+I)},fa.qa);b={};V.UseHybrid&&0<F.length&&(b.fontactive=function(){Wa(a,a.U,!0)},b.fontinactive=function(){Wa(a,a.U,!0)});1==V.EnableCustomFOUTHandler&&Oa(new Na(a.c,a.a,new Ba(a.a,document.documentElement,b),fa.qa),F,{},{},!1)}}}}mti.ra=function(a){this.Ga=a};
mti.ra.prototype={Ka:function(a,c){ib(this.Ga,a,c)}};
mti.o.prototype.xa=function(){var a=this,c="";if(window.MutationObserver){var b=new MutationObserver(function(b){b.forEach(function(b){if("characterData"==b.type)null!=b.target.parentNode&&(d=b.target.parentNode,"undefined"!==typeof d.getAttribute("isRender")&&"true"!==d.getAttribute("isRender")?(d.setAttribute("isRender","true"),null!=b.target.parentNode.id&&void 0!=typeof b.target.parentNode.id&&"undefined"!==typeof document.getElementById(b.target.parentNode.id)&&null!=document.getElementById(b.target.parentNode.id)&&
(c=document.getElementById(b.target.parentNode.id).getAttribute("data-mti-otf")),void 0!=typeof c&&"mti-otf"!=c&&kb(a,b.target.parentNode)):setTimeout(function(){d.removeAttribute("isRender")},0));else if("attributes"==b.type&&"style"==b.attributeName){var d=b.target;"BESb\uc5d0swy"!=d.innerHTML&&"BESbswy"!=d.innerHTML&&("undefined"!==typeof d.getAttribute("isRender")&&"true"!==d.getAttribute("isRender")?(d.setAttribute("isRender","true"),null!=d.id&&""!=d.id&&void 0!=typeof d.id?"undefined"!==typeof document.getElementById(d.id)&&
null!=document.getElementById(d.id)&&(c=document.getElementById(d.id).getAttribute("data-mti-otf")):null!=d&&""!=d&&void 0!=typeof d&&(c=d.getAttribute("data-mti-otf")),d=null!=d.id?d.id:d,"mti-otf"!=c&&""!=d&&kb(a,d)):setTimeout(function(){d.removeAttribute("isRender")},0))}else if("childList"==b.type&&0<b.addedNodes.length)for(var g=0;g<b.addedNodes.length;g++)if(d=b.addedNodes[g],3==d.nodeType&&(d=d.parentNode),"undefined"!==typeof d&&null!=d&&3!=d.nodeType){var h=d.tagName;"HTML"!=h&&"HEAD"!=
h&&"TITLE"!=h&&"STYLE"!=h&&"LINK"!=h&&"META"!=h&&"BASE"!=h&&"IMG"!=h&&"HR"!=h&&"BR"!=h&&"BESb\uc5d0swy"!=d.innerHTML&&"BESbswy"!=d.innerHTML&&"undefined"!==typeof d.className&&"function"===typeof d.className.indexOf&&-1==d.className.indexOf("firebugLayoutBox")&&(null!=d.id&&""!=d.id&&void 0!=typeof d.id?null!=document.getElementById(d.id)&&(c=document.getElementById(d.id).getAttribute("data-mti-otf")):null!=d&&""!=d&&void 0!=typeof d&&(c=d.getAttribute("data-mti-otf")),d="undefined"!==typeof d.id&&
null!=d.id&&""!=d.id?d.id:d,"mti-otf"!=c&&""!=d&&kb(a,d))}});lb(a,!0)});document.body&&b.observe(document.body,{childList:!0,characterData:!0,subtree:!0,attributes:!0})}else b=function(a,b){var c=document;c.addEventListener?c.addEventListener(a,b,!1):c.attachEvent("on"+a,b)},b("DOMNodeInserted",function(b){b=b.target;void 0!=typeof b&&null!=b&&3==b.nodeType&&(b=b.parentElement);if(void 0!=typeof b&&null!=b&&1==b.nodeType){var e=b.tagName;"HTML"!=e&&"HEAD"!=e&&"TITLE"!=e&&"STYLE"!=e&&"LINK"!=e&&"META"!=
e&&"BASE"!=e&&"IMG"!=e&&"HR"!=e&&"BR"!=e&&"BESb\uc5d0swy"!=b.innerHTML&&"BESbswy"!=b.innerHTML&&(void 0!=typeof b.id&&null!=b.id&&""!=b.id?"undefined"!==typeof document.getElementById(b.id)&&null!=document.getElementById(b.id)&&(c=document.getElementById(b.id).getAttribute("data-mti-otf")):void 0!=typeof b.getAttribute&&void 0!=typeof b&&null!=b&&""!=b&&(c=b.getAttribute("data-mti-otf")),"mti-otf"!=c&&""!=b&&(kb(a,b),lb(a,!1)))}}),b("DOMAttrModified",function(b){if("style"==b.attrName){var e=b.target;
"BESb\uc5d0swy"!=e.innerHTML&&"BESbswy"!=e.innerHTML&&("undefined"!==typeof e.getAttribute("isRender")&&"true"!==e.getAttribute("isRender")?(e.setAttribute("isRender","true"),void 0!=typeof e.id&&null!=e.id&&""!=e.id?void 0!=typeof document.getElementById(e.id)&&null!=document.getElementById(e.id)&&(c=document.getElementById(e.id).getAttribute("data-mti-otf")):void 0!=typeof e.getAttribute("data-mti-otf")&&null!=e&&""!=e&&(c=e.getAttribute("data-mti-otf")),"mti-otf"!=c&&""!=e&&(kb(a,e),lb(a,!1))):
setTimeout(function(){e.removeAttribute("isRender")},0))}}),b("DOMCharacterDataModified",function(b){b=b.target;void 0!=typeof b&&null!=b&&3==b.nodeType&&(b=b.parentElement);if(void 0!=typeof b&&null!=b&&1==b.nodeType){var e=b.tagName;"HTML"!=e&&"HEAD"!=e&&"TITLE"!=e&&"STYLE"!=e&&"LINK"!=e&&"META"!=e&&"BASE"!=e&&"IMG"!=e&&"HR"!=e&&"BR"!=e&&"BESb\uc5d0swy"!=b.innerHTML&&"BESbswy"!=b.innerHTML&&(void 0!=typeof b.id&&null!=b.id&&""!=b.id?null!=document.getElementById(b.id)&&(c=document.getElementById(b.id).getAttribute("data-mti-otf")):
void 0!=typeof b&&null!=b&&""!=b&&(c=b.getAttribute("data-mti-otf")),"mti-otf"!=c&&""!=b&&(kb(a,b),lb(a,!1)))}})};
function kb(a,c){if(void 0!=typeof c&&null!=c){var b,d,e="";"string"==typeof c?(b=document.getElementById(c),null!=b&&(d=b.parentNode),null!=d&&(e=b.getAttribute("id")),-1==a.a.indexOf(a.B,c)&&-1==a.a.indexOf(a.B,e)&&a.B.push(c)):-1==a.a.indexOf(a.B,c)&&-1==a.a.indexOf(a.B,c.parentElement)&&a.B.push(c);1==V.EnableCustomFOUTHandler&&(c="string"==typeof c?document.getElementById(c):c,1==c.nodeType&&mb(a,c).w&&(G(c,"mti_hide_element"),setTimeout(function(){1==V.EnableCustomFOUTHandler&&jb(a,"mti_hide_element")},
75)))}}mti.o.prototype.oa=null;
function lb(a,c){var b=50;c||(b=0);a.f.enableOtf&&(b=0);null!=a.oa&&clearTimeout(a.oa);a.oa=setTimeout(function(){if(-1<a.B.length){var b="";if(!(1>a.B.length)){for(var c=0;c<a.B.length;c++){var f="string"==typeof a.B[c]?document.getElementById(a.B[c]):a.B[c];if(void 0!=typeof f&&null!=f){var b=oa(a.a,f),g=new W(f,a.a,a.f.pfL),h=g.K(f),g=g.C,k=mb(a,f);k.w?""!=b?nb(a,a.B[c],b,k,h,g):(b="_n4",a.l&&(b=k.fontStyle.charAt(0)+k.fontWeight/100),null!=h&&(b=h[k.R+b],nb(a,a.B[c],b,k,h,g))):!k.w&&null!=f&&
f.hasChildNodes&&(k=ob(a,f),b=oa(a.a,k.node),g=new W(k.node,a.a,a.f.pfL),h=g.K(k.node),g=g.C,k.w&&nb(a,k.node,b,k,h,g))}}a.B=[]}}},b)}
function mb(a,c){if(1!=c.nodeType)return{w:!1};var b=a.a.getComputedStyle(c),d="test",e="normal",f="100";if(void 0!=typeof b&&null!=b)if(d=b.fontFamily,e=b.fontStyle,f="normal"==b.fontWeight?"400":"bold"==b.fontWeight?"700":b.fontWeight,b=null!=d?d.split(","):"",b instanceof Array)for(d=0;d<b.length;d++)for(var g=0;g<a.f.pfL.length;g++){var h=a.f.pfL[g],k=h.fontfamily,m=h.enableSubsetting,l=h.fontStyle,v=h.fontWeight,h=h.enableOtf;if(k==J(b[d])&&(m||h))if(a.v){if(l==e&&v==f)return{w:!0,R:k,fontWeight:f,
fontStyle:e}}else return{w:!0,R:k}}else for(d=0;d<a.f.pfL.length;d++)if(h=a.f.pfL[d],k=h.fontfamily,m=h.enableSubsetting,l=h.fontStyle,v=h.fontWeight,h=h.enableOtf,m||h)if(a.v){if(l==e&&v==f)return{w:!0,R:k,fontWeight:f,fontStyle:e}}else if(k==J(b))return{w:!0,R:k};return{w:!1}}function ob(a,c){var b={w:!1,R:"testFont"};if(1==c.nodeType&&(b=mb(a,c),b.w))return b.node=c,b;for(var d=c.childNodes,e=d.length,f=0;f<e;f++){var g=d[f];if(1==g.nodeType&&(b=ob(a,g),b.w))break}return b}
function qb(a,c,b){var d="string"==typeof c?document.getElementById(c):c;if(null!==d){var e=!0,f=[];a.h=[];var g=a.f.projectId,h=a.f.fcURL,k=a.f.ck,m="",l,v,e=!0;if(V.UseHybrid){var e=!1,z=a.a.getElementById("mti_fontface_"+g);null==z&&(z=a.a.createElement("style",{type:"text/css",id:"mti_fontface_"+g}),D(a.a,"head",z));var r=d.getAttribute("data-mtiFont"),y=a.a.getComputedStyle(d);null==r&&(r=y.fontFamily.replace(/^\s|\s$/g,"").replace(/'|"/g,""));for(var u=[],n=0;n<a.f.pfL.length;n++)u.push(a.f.pfL[n].fontfamily);
if(d.hasChildNodes&&0>a.a.indexOf(u,r))for(n=d.childNodes,t=0;t<n.length&&!(1==n[t].nodeType&&(r=a.a.A(n[t]).replace(/^\s|\s$/g,"").replace(/'|"/g,""),-1<a.a.indexOf(u,r)));t++);for(var u="normal"==y.fontWeight?"400":"bold"==y.fontWeight?"700":y.fontWeight,y=y.fontStyle,x=y.charAt(0)+u/100,r=r.split(","),t=0;t<r.length;t++){for(var q,n=0;n<a.f.pfL.length;n++){q=a.f.pfL[n];var p=q.fontfamily,w=p+"_n4_f";r[t]==p&&q.enableSubsetting&&(a.l?(l=q.fontWeight,v=q.fontStyle,y==q.fontStyle&&u==q.fontWeight&&
(x=v.charAt(0)+l/100,w=(25<p.length?p.substring(0,20):p)+"_"+x+"_f",a.h.push(new T(p,x)),f.push(new T(p,x)))):(x="n4",a.h.push(new T(p)),f.push(new T(p))));Z(w)&&(e=!1,-1==a.a.indexOf(a.M,p+"_"+x)&&(contentIdArray=q.contentIds,enableOtf=q.enableOtf,fFormat=a.S(contentIdArray),fontURL=Y(a,contentIdArray,g,!1,h,"",k,p,l,v,null,fFormat,enableOtf),""!=fontURL&&(m+='@font-face{\nfont-family:"'+p+'";',a.l&&(m+="\nfont-style:"+v+";",m+="\nfont-weight:"+l+";"),m+='\nsrc:url("'+fontURL+'")',m+=";}\n",a.$[p+
"_"+x]=eb(a,"",p+"_"+x))))}if(""!=m){z.styleSheet?z.styleSheet.cssText+=m:z.innerHTML+=m;d.removeAttribute("data-mtiFont");n="";if(d.hasChildNodes())for(n=d.childNodes,q=0;q<n.length;q++)1==n[q].nodeType&&n[q].getAttribute("data-mtiFont")&&(n[q].style.fontFamily=n[q].getAttribute("data-mtiFont"),n[q].removeAttribute("data-mtiFont"));if(null!=a.j){var B=new W(null!=d&&d!=document.body?d.parentElement:document.body,a.a,a.f.pfL);B.K({},A);mti.bind(a.j,a.j.ea,B.C)()}}else e=!0}}if(e){var A=gb(),H=B=null,
I=[],M=null!=d&&d!=document.body?d.parentElement:document.body;if(null==d.parentElement||b)M=document.body;(function(){B=new W(M,a.a,a.f.pfL);H=B.K({},A);var b=[];if(void 0!=H)for(var e in H)e+=A,b.push(new T(g));a.T.mti_element_cache=B.C;Ya(a,B.Y(),H,A,!0);b=B.C;null!=a.j&&mti.bind(a.j,a.j.ea,b)();for(e=0;e<b.length;e++)for(var g in a.m)-1<a.a.indexOf(a.a.A(b[e]),g)&&(b[e].getAttribute("id")==c||b[e]==c?a.a.F(b[e],g,a.m[g],!1,a.v):sa(d,b[e])&&-1<a.a.indexOf(a.a.A(b[e]).replace(/'|"/g,""),g)&&a.a.F(b[e],
g,a.m[g],!1,a.v));e=null==a.m[g]?0:a.m[g].length;if(0<a.h.length)for(b=0;b<a.h.length;b++)a.h[b].enableSubsetting&&(g=a.h[b].getName()+A,e=null,a.l&&(e=S(a.h[b])),g=null!=e?new T(g,e):new T(g),f.push(g));else for(b=0;b<e;b++)a.l?f.push(new T(a.m[g][b],"i6")):f.push(new T(a.m[g][b])),-1==a.a.indexOf(a.ha,g)&&(a.ha.push(g),a.l?I.push(new T(a.m[g][b],"i6")):I.push(new T(a.m[g][b])))})();1==V.RemoveMTIClass&&setTimeout(function(){jb(a,"mti_font_element"+A)},5E3)}b={};0<f.length&&(b.fontactive=function(b,
c,d){V.UseHybrid&&Wa(a,a.U,!0);for(var e=0;e<window.MonoTypeWebFonts._fontActiveEventList.length;e++)d=b.slice(0,-5),window.MonoTypeWebFonts._fontActiveEventList[e].call(window.MonoTypeWebFonts,b,c,d)},b.inactive=function(a,b,c){for(var d=0;d<window.MonoTypeWebFonts._inActiveEventList.length;d++)c=a.slice(0,-5),window.MonoTypeWebFonts._inActiveEventList[d].call(window.MonoTypeWebFonts,a,b,c)},b.fontloading=function(a,b,c){for(var d=0;d<window.MonoTypeWebFonts._fontLoadingEventList.length;d++)c=a.slice(0,
-5),window.MonoTypeWebFonts._fontLoadingEventList[d].call(window.MonoTypeWebFonts,a,b,c)},b.active=function(){for(var a=0;a<window.MonoTypeWebFonts._activeEventList.length;a++)window.MonoTypeWebFonts._activeEventList[a].call(window.MonoTypeWebFonts)});1==V.EnableCustomFOUTHandler&&Oa(new Na(a.c,a.a,new Ba(a.a,document.documentElement,b),5E3),f,{},{},!1)}}
function nb(a,c,b,d,e,f){var g=c;"string"==typeof c&&(g=document.getElementById(g));d=c==d.node?!0:!1;var h=ta(b).split("").sort().join("");if(null!=e)for(var k in e){if(""!=e[k]){var m=k.slice(0,-3);fntVariant=k.slice(-3);b=eb(a,h,m+"abcde"+(a.l?fntVariant:""),!0);var l=a.$[k];if(-1==a.a.indexOf(a.M,k))if(V.UseHybrid)if(Z(k+"_f"))qb(a,c,d);else if(b!=l){for(var v in f)b=mb(a,f[v]),b.w&&(b=oa(a.a,f[v]),""!=b&&(l=eb(a,"",m+"abcde"+fntVariant,!0),b=ta(b).split("").sort().join(""),l=ta(l),hb(l,b)||qb(a,
f[v],d)));qb(a,c,d)}else null!=a.j&&rb(a,c),-1<a.ba.indexOf(k+"_f")&&-1==a.M.indexOf(k)&&(textCollector=new W(g,a.a,a.f.pfL),e=textCollector.K({}),Ya(a,textCollector.Y(),e));else if(b!=l)qb(a,c,d);else{var l=a.a.A(g),z=g.getAttribute("data-mtiFont"),r=!0;b=mb(a,g);b.w&&a.l&&(r=a.a.getComputedStyle(g),l=r.fontFamily,fntStyle=r.fontStyle,fntWeight=r.fontWeight,r=fntStyle==b.fontStyle&&fntWeight==b.fontWeight?!0:!1);if(-1==l.indexOf(a.V[m])&&-1<l.indexOf(z)&&0==a.V[m].indexOf(z)&&r)a.a.F(g,m,a.V[m],
!1,!1);else for(v in f)b=mb(a,f[v]),b.w&&b.R===m&&(l=a.a.A(f[v]),r=!0,a.l&&(r=a.a.getComputedStyle(f[v]),l=r.fontFamily,fntStyle=r.fontStyle,fntWeight=r.fontWeight,r=fntStyle==b.fontStyle&&fntWeight==b.fontWeight?!0:!1),-1==l.indexOf(a.V[m])&&r&&a.a.F(f[v],m,a.V[m],!1,!1));null!=a.j&&rb(a,c)}else null!=a.j&&rb(a,c)}}else null!=a.j&&rb(a,c)}
function rb(a,c){var b="string"==typeof c?document.getElementById(c):c,d=new W(null!=b?c.parentElement:document.body,a.a,a.f.pfL);d.K({});d=d.C;0==d.length&&d.push(b);mti.bind(a.j,a.j.ea,d)()};function Z(a){a=a.replace(/\s+/g,"%20");a=document.cookie.split(a+"=");var c=null;2==a.length&&(c=a.pop().split(";").shift());return 1==c?!0:!1}
function eb(a,c,b,d){d&&(b=a.v?b.substring(0,b.length-8)+b.substring(b.length-3,b.length):b.substring(0,b.length-5));if("undefined"!==typeof Storage){a:{var e;try{e=window.localStorage.getItem(b)}catch(f){console&&console.log("MTI_webfont_service::localStorage.getItem error::"+f.message);a=!1;break a}a=null==e?!1:e.length>c.length?hb(e,c)?e:!1:!1}if(0==a&&c){a=c;try{null!=window.localStorage.getItem(b)&&(a+=window.localStorage.getItem(b)),a=ta(a).split("").sort().join(""),window.localStorage.setItem(b,
a)}catch(g){console&&console.log("MTI_webfont_service::localStorage.setItem error::"+g.message)}}else if(0<a.length)return a}return c};function jb(a,c){for(var b=pa(a.a,c),d=new RegExp(c,"ig");0<b.length;){for(var e=0;e<b.length;e++)1!=b[e].className.split(" ").length||a.na?b[e].className=b[e].className.replace(d," ").replace(/^\s+|\s+$/g,""):b[e].removeAttribute("class");b=pa(a.a,c)}}
mti.o.prototype.F=function(a,c,b,d,e){var f=this.A(a).split(","),g=[];if(b instanceof Array){for(var h in b)b.hasOwnProperty(h)&&g.push(b[h]);d&&(e&&(b=na(this,a),d=ma(this,a),g.push(c+"_"+b.charAt(0)+d/100)),a.style.fontWeight="",a.style.fontStyle="");for(h in f)f.hasOwnProperty(h)&&g.push(f[h]);g=ra(g);a.style.fontFamily=g;a.setAttribute("data-mtiFont",c)}};
function Xa(a,c){if(!0===mti.o.b)c();else{var b=a.a.D;if("MSIE"==a.c.getName()){var d=!1,e=function(){d||(d=!0,c(),mti.o.b=!0)};(function(){try{if("msie"==a.I&&11<=a.version.i?b.documentElement.scrollLeft:b.documentElement.doScroll("left"),"complete"!=b.readyState){setTimeout(arguments.callee,50);return}}catch(c){setTimeout(arguments.callee,50);return}e()})();b.onreadystatechange=function(){"complete"==b.readyState&&(b.onreadystatechange=null,e())}}else"AppleWebKit"==a.c.Ba&&525>a.c.Aa.i?function(){-1<
["loaded","complete"].indexOf(b.readyState)?(c(),mti.o.b=!0):setTimeout(arguments.callee,50)}():b.addEventListener?"loading"==b.readyState?b.addEventListener("DOMContentLoaded",function(){c();mti.o.b=!0},!1):window.onload=function(){c();mti.o.b=!0}:window.onload=function(){c();mti.o.b=!0}}}
function Wa(a,c,b){"complete"==document.readyState?setTimeout(function(){c.apply(a,[a.h,b,!1])},500):document.addEventListener("readystatechange",function(){"complete"==document.readyState&&setTimeout(function(){c.apply(a,[a.h,b,!1])},500)});document.addEventListener?document.addEventListener("keydown",function(b){a.pa.apply(a,[b])}):window.attachEvent?window.attachEvent("onkeydown",function(b){a.pa.apply(a,[b])}):document.addEventListener("keydown",function(b){a.pa.apply(a,[b])})};
})(this,document);